package com.novoseltech.handymano;


import android.util.Log;
import java.util.ArrayList;

/**
 @author Denis Novosel
 @student_id 17104718
 @email x17104718@student.ncirl.ie
 @github https://github.com/adminnovoseltech/SoftwareProjectDN17104718
 @class Functions.java
 **/

public class Functions {


    public boolean containsOffensiveWord(String sentence){
        //List of offensive words retrieved from https://www.cs.cmu.edu/~biglou/resources/bad-words.txt

        //Idea based on https://stackoverflow.com/questions/33254492/how-to-censored-bad-words-offensive-words-in-android-studio/33254897
        boolean contains = false;
        ArrayList<String> offensiveWords = new ArrayList<>();
        /*String list =   "allah," +
                        "anal," +
                        "analannie," +
                        "analsex," +
                        "anus," +
                        "areola," +
                        "arsehole," +
                        "ass," +
                        "assassin," +
                        "assassinate," +
                        "assassination," +
                        "assault," +
                        "assbagger," +
                        "assblaster," +
                        "assclown," +
                        "asscowboy," +
                        "asses," +
                        "assfuck," +
                        "assfucker," +
                        "asshat," +
                        "asshole," +
                        "assholes," +
                        "asshore," +
                        "assjockey," +
                        "asskiss," +
                        "asskisser," +
                        "assklown," +
                        "asslick," +
                        "asslicker," +
                        "asslover," +
                        "assman," +
                        "assmonkey," +
                        "assmunch," +
                        "assmuncher," +
                        "asspacker," +
                        "asspirate," +
                        "asspuppies," +
                        "assranger," +
                        "asswhore," +
                        "asswipe," +
                        "athletesfoot," +
                        "attack," +
                        "babe," +
                        "babies," +
                        "badfuck," +
                        "balllicker," +
                        "balls," +
                        "ballsack," +
                        "banging," +
                        "baptist," +
                        "barelylegal," +
                        "barf," +
                        "barface," +
                        "barfface," +
                        "bast," +
                        "bastard ," +
                        "bazongas," +
                        "bazooms," +
                        "beaner," +
                        "beast," +
                        "beastality," +
                        "beastial," +
                        "beastiality," +
                        "beatoff," +
                        "beat-off," +
                        "beatyourmeat," +
                        "bestial," +
                        "bestiality," +
                        "biatch," +
                        "bicurious," +
                        "bigass," +
                        "bigbastard," +
                        "bigbutt," +
                        "bigger," +
                        "bisexual," +
                        "bi-sexual," +
                        "bitch," +
                        "bitcher," +
                        "bitches," +
                        "bitchez," +
                        "bitchin," +
                        "bitching," +
                        "bitchslap," +
                        "bitchy," +
                        "biteme," +
                        "blowjob," +
                        "boang," +
                        "bogan," +
                        "bohunk," +
                        "bollick," +
                        "bollock," +
                        "bomb," +
                        "bombers," +
                        "bombing," +
                        "bombs," +
                        "bomd," +
                        "bondage," +
                        "boner," +
                        "bong," +
                        "boob," +
                        "boobies," +
                        "boobs," +
                        "booby," +
                        "boody," +
                        "boom," +
                        "boong," +
                        "boonga," +
                        "boonie," +
                        "booty," +
                        "bootycall," +
                        "bountybar," +
                        "brea5t," +
                        "breast," +
                        "breastjob," +
                        "breastlover," +
                        "breastman," +
                        "bugger," +
                        "buggered," +
                        "buggery," +
                        "bullcrap," +
                        "bulldike," +
                        "bulldyke," +
                        "bullshit," +
                        "bumblefuck," +
                        "bumfuck," +
                        "bunga," +
                        "bunghole," +
                        "buried," +
                        "burn," +
                        "butchbabes," +
                        "butchdike," +
                        "butchdyke," +
                        "butt," +
                        "buttbang," +
                        "butt-bang," +
                        "buttface," +
                        "buttfuck," +
                        "butt-fuck," +
                        "buttfucker," +
                        "butt-fucker," +
                        "buttfuckers," +
                        "butt-fuckers," +
                        "butthead," +
                        "buttman," +
                        "buttmunch," +
                        "buttmuncher," +
                        "buttpirate," +
                        "buttplug," +
                        "buttstain," +
                        "byatch," +
                        "cacker," +
                        "cameljockey," +
                        "cameltoe," +
                        "cancer," +
                        "carpetmuncher," +
                        "carruth," +
                        "cherrypopper," +
                        "chickslick," +
                        "children's," +
                        "clamdigger," +
                        "clamdiver," +
                        "clitoris," +
                        "cocaine," +
                        "cock," +
                        "cockblock," +
                        "cockblocker," +
                        "cockcowboy," +
                        "cockfight," +
                        "cockhead," +
                        "cockknob," +
                        "cocklicker," +
                        "cocklover," +
                        "cocknob," +
                        "cockqueen," +
                        "cockrider," +
                        "cocksman," +
                        "cocksmith," +
                        "cocksmoker," +
                        "cocksucer," +
                        "cocksuck ," +
                        "cocksucked ," +
                        "cocksucker," +
                        "cocksucking," +
                        "cocktease," +
                        "cohee," +
                        "coitus," +
                        "condom," +
                        "conservative," +
                        "conspiracy," +
                        "coolie," +
                        "cooly," +
                        "coon," +
                        "coondog," +
                        "copulate," +
                        "cornhole," +
                        "corruption," +
                        "cra5h," +
                        "crackpipe," +
                        "crackwhore," +
                        "crack-whore," +
                        "crapola," +
                        "crapper," +
                        "crappy," +
                        "crash," +
                        "creamy," +
                        "crime," +
                        "crimes," +
                        "criminal," +
                        "criminals," +
                        "crotch," +
                        "crotchjockey," +
                        "crotchmonkey," +
                        "crotchrot," +
                        "cumbubble," +
                        "cumfest," +
                        "cumjockey," +
                        "cummer," +
                        "cumming," +
                        "cumquat," +
                        "cumqueen," +
                        "cumshot," +
                        "cunilingus," +
                        "cunillingus," +
                        "cunnilingus," +
                        "cunntt," +
                        "cunteyed," +
                        "cuntfuck," +
                        "cuntfucker," +
                        "cuntlick ," +
                        "cuntlicker ," +
                        "cuntlicking ," +
                        "cuntsucker," +
                        "cybersex," +
                        "cyberslimer," +
                        "dahmer," +
                        "dammit," +
                        "damn," +
                        "damnation," +
                        "damnit," +
                        "datnigga," +
                        "deapthroat," +
                        "death," +
                        "deepthroat," +
                        "defecate," +
                        "destroy," +
                        "devilworshipper," +
                        "dick," +
                        "dickbrain," +
                        "dickforbrains," +
                        "dickhead," +
                        "dickless," +
                        "dicklick," +
                        "dicklicker," +
                        "dickman," +
                        "dickwad," +
                        "dickweed," +
                        "diddle," +
                        "died," +
                        "dies," +
                        "dike," +
                        "dildo," +
                        "dingleberry," +
                        "dink," +
                        "dipshit," +
                        "dipstick," +
                        "dirty," +
                        "disease," +
                        "diseases," +
                        "disturbed," +
                        "dixiedike," +
                        "dixiedyke," +
                        "doggiestyle," +
                        "doggystyle," +
                        "dong," +
                        "doodoo," +
                        "doo-doo," +
                        "doom," +
                        "dope," +
                        "dragqueen," +
                        "dragqween," +
                        "dripdick," +
                        "drug," +
                        "drunk," +
                        "drunken," +
                        "dumb," +
                        "dumbass," +
                        "dumbbitch," +
                        "dumbfuck," +
                        "easyslut," +
                        "eatballs," +
                        "eatpussy," +
                        "ecstacy," +
                        "ejaculate," +
                        "ejaculated," +
                        "ejaculating ," +
                        "ejaculation," +
                        "erection," +
                        "excrement," +
                        "execute," +
                        "executed," +
                        "execution," +
                        "executioner," +
                        "explosion," +
                        "facefucker," +
                        "faeces," +
                        "fagging," +
                        "faggot," +
                        "fagot," +
                        "failed," +
                        "failure," +
                        "fairies," +
                        "fairy," +
                        "faith," +
                        "fannyfucker," +
                        "fart," +
                        "farted ," +
                        "farting ," +
                        "farty ," +
                        "fastfuck," +
                        "fatah," +
                        "fatass," +
                        "fatfuck," +
                        "fatfucker," +
                        "feces," +
                        "felatio ," +
                        "fetish," +
                        "fight," +
                        "fingerfood," +
                        "fingerfuck ," +
                        "fingerfucked ," +
                        "fingerfucker ," +
                        "fingerfuckers," +
                        "fingerfucking ," +
                        "fistfuck," +
                        "fistfucked ," +
                        "fistfucker ," +
                        "fistfucking ," +
                        "fisting," +
                        "flange," +
                        "flasher," +
                        "flatulence," +
                        "flydie," +
                        "flydye," +
                        "fondle," +
                        "footaction," +
                        "footfuck," +
                        "footfucker," +
                        "footlicker," +
                        "footstar," +
                        "foreskin," +
                        "fornicate," +
                        "foursome," +
                        "fourtwenty," +
                        "fraud," +
                        "freakfuck," +
                        "freakyfucker," +
                        "freefuck," +
                        "fubar," +
                        "fucck," +
                        "fuck," +
                        "fucka," +
                        "fuckable," +
                        "fuckbag," +
                        "fuckbuddy," +
                        "fucked," +
                        "fuckedup," +
                        "fucker," +
                        "fuckers," +
                        "fuckface," +
                        "fuckfest," +
                        "fuckfreak," +
                        "fuckfriend," +
                        "fuckhead," +
                        "fuckher," +
                        "fuckin," +
                        "fuckina," +
                        "fucking," +
                        "fuckingbitch," +
                        "fuckinnuts," +
                        "fuckinright," +
                        "fuckit," +
                        "fuckknob," +
                        "fuckme ," +
                        "fuckmehard," +
                        "fuckmonkey," +
                        "fuckoff," +
                        "fuckpig," +
                        "fucks," +
                        "fucktard," +
                        "fuckwhore," +
                        "fuckyou," +
                        "fudgepacker," +
                        "fugly," +
                        "funfuck," +
                        "fungus," +
                        "fuuck," +
                        "gangbang," +
                        "gangbanged ," +
                        "gangbanger," +
                        "gangsta," +
                        "gatorbait," +
                        "gaymuthafuckinwhore," +
                        "gaysex ," +
                        "geez," +
                        "geezer," +
                        "geni," +
                        "genital," +
                        "getiton," +
                        "givehead," +
                        "glazeddonut," +
                        "godammit," +
                        "goddamit," +
                        "goddammit," +
                        "goddamn," +
                        "goddamned," +
                        "goddamnes," +
                        "goddamnit," +
                        "goddamnmuthafucker," +
                        "goldenshower," +
                        "gonorrehea," +
                        "gonzagas," +
                        "goyim," +
                        "greaseball," +
                        "gringo," +
                        "groe," +
                        "gross," +
                        "grostulation," +
                        "gubba," +
                        "gummer," +
                        "gypo," +
                        "gypp," +
                        "gyppie," +
                        "gyppo," +
                        "gyppy," +
                        "hamas," +
                        "handjob," +
                        "hapa," +
                        "harder," +
                        "hardon," +
                        "harem," +
                        "headfuck," +
                        "headlights," +
                        "hebe," +
                        "heeb," +
                        "henhouse," +
                        "heroin," +
                        "herpes," +
                        "heterosexual," +
                        "hijack," +
                        "hijacker," +
                        "hijacking," +
                        "hillbillies," +
                        "hindoo," +
                        "hiscock," +
                        "hitler," +
                        "hitlerism," +
                        "hitlerist," +
                        "hodgie," +
                        "holestuffer," +
                        "homicide," +
                        "homobangers," +
                        "homosexual," +
                        "honger," +
                        "honkers," +
                        "honkey," +
                        "honky," +
                        "hooker," +
                        "hookers," +
                        "hooters," +
                        "horney," +
                        "horniest," +
                        "horny," +
                        "horseshit," +
                        "hosejob," +
                        "hoser," +
                        "hostage," +
                        "hotdamn," +
                        "hotpussy," +
                        "hottotrot," +
                        "hustler," +
                        "hymen," +
                        "hymie," +
                        "iblowu," +
                        "idiot," +
                        "illegal," +
                        "incest," +
                        "insest," +
                        "intercourse," +
                        "interracial," +
                        "intheass," +
                        "inthebuff," +
                        "jackass," +
                        "jackoff," +
                        "jackshit," +
                        "jacktheripper," +
                        "japanese," +
                        "japcrap," +
                        "jebus," +
                        "jerkoff," +
                        "jigaboo," +
                        "jigga," +
                        "jiggabo," +
                        "jigger ," +
                        "jiggy," +
                        "jihad," +
                        "jijjiboo," +
                        "jimfish," +
                        "jism," +
                        "jizim," +
                        "jizjuice," +
                        "jizzim," +
                        "jizzum," +
                        "joint," +
                        "juggalo," +
                        "junglebunny," +
                        "kaffer," +
                        "kaffir," +
                        "kaffre," +
                        "kafir," +
                        "kanake," +
                        "kigger," +
                        "kike," +
                        "kill," +
                        "killed," +
                        "killer," +
                        "killing," +
                        "kills," +
                        "kink," +
                        "kinky," +
                        "kissass," +
                        "kkk," +
                        "knife," +
                        "knockers," +
                        "kock," +
                        "kondum," +
                        "koon," +
                        "kotex," +
                        "krap," +
                        "krappy," +
                        "kraut," +
                        "kum," +
                        "kumbubble," +
                        "kumbullbe," +
                        "kummer," +
                        "kumming," +
                        "kumquat," +
                        "kums," +
                        "kunilingus," +
                        "kunnilingus," +
                        "kunt," +
                        "kyke," +
                        "lactate," +
                        "lapdance," +
                        "latin," +
                        "lesbain," +
                        "lesbayn," +
                        "lesbian," +
                        "lesbin," +
                        "lesbo," +
                        "lezbe," +
                        "lezbefriends," +
                        "lezbo," +
                        "lezz," +
                        "lezzo," +
                        "liberal," +
                        "libido," +
                        "licker," +
                        "lickme," +
                        "lingerie," +
                        "liquor," +
                        "livesex," +
                        "loadedgun," +
                        "lolita," +
                        "looser," +
                        "loser," +
                        "lotion," +
                        "lovebone," +
                        "lovegoo," +
                        "lovegun," +
                        "lovejuice," +
                        "lovemuscle," +
                        "lovepistol," +
                        "loverocket," +
                        "lowlife," +
                        "lubejob," +
                        "lugan," +
                        "lynch," +
                        "macaca," +
                        "mafia," +
                        "magicwand," +
                        "manhater," +
                        "manpaste," +
                        "marijuana," +
                        "mastabate," +
                        "mastabater," +
                        "masterbate," +
                        "masterblaster," +
                        "mastrabator," +
                        "masturbate," +
                        "masturbating," +
                        "mattressprincess," +
                        "meatbeatter," +
                        "meatrack," +
                        "mgger," +
                        "mggor," +
                        "mickeyfinn," +
                        "mideast," +
                        "milf," +
                        "minority," +
                        "mockey," +
                        "mockie," +
                        "mocky," +
                        "moles," +
                        "molest," +
                        "molestation," +
                        "molester," +
                        "molestor," +
                        "moneyshot," +
                        "mooncricket," +
                        "mormon," +
                        "moron," +
                        "moslem," +
                        "mosshead," +
                        "mothafuck," +
                        "mothafucka," +
                        "mothafuckaz," +
                        "mothafucked ," +
                        "mothafucker," +
                        "mothafuckin," +
                        "mothafucking ," +
                        "mothafuckings," +
                        "motherfuck," +
                        "motherfucked," +
                        "motherfucker," +
                        "motherfuckin," +
                        "motherfucking," +
                        "motherfuckings," +
                        "motherlovebone," +
                        "muffdive," +
                        "muffdiver," +
                        "muffindiver," +
                        "mufflikcer," +
                        "mulatto," +
                        "muncher," +
                        "murder," +
                        "murderer," +
                        "muslim," +
                        "naked," +
                        "narcotic," +
                        "nasty," +
                        "nastybitch," +
                        "nastyho," +
                        "nastyslut," +
                        "nastywhore," +
                        "necro," +
                        "negro," +
                        "negroes," +
                        "negroid," +
                        "negro's," +
                        "nig," +
                        "niger," +
                        "nigerian," +
                        "nigerians," +
                        "nigg," +
                        "nigga," +
                        "niggah," +
                        "niggaracci," +
                        "niggard," +
                        "niggarded," +
                        "niggarding," +
                        "niggardliness," +
                        "niggardliness's," +
                        "niggardly," +
                        "niggards," +
                        "niggard's," +
                        "niggaz," +
                        "nigger," +
                        "niggerhead," +
                        "niggerhole," +
                        "niggers," +
                        "nigger's," +
                        "niggle," +
                        "niggled," +
                        "niggles," +
                        "niggling," +
                        "nigglings," +
                        "niggor," +
                        "niggur," +
                        "niglet," +
                        "nignog," +
                        "nigr," +
                        "nigra," +
                        "nigre," +
                        "nipple," +
                        "nipplering," +
                        "nittit," +
                        "nlgger," +
                        "nlggor," +
                        "nofuckingway," +
                        "nookey," +
                        "nookie," +
                        "noonan," +
                        "nooner," +
                        "nude," +
                        "nudger," +
                        "nutfucker," +
                        "nymph," +
                        "ontherag," +
                        "oral," +
                        "orga," +
                        "orgasim ," +
                        "orgasm," +
                        "orgies," +
                        "orgy," +
                        "osama," +
                        "paki," +
                        "palesimian," +
                        "palestinian," +
                        "pansies," +
                        "pansy," +
                        "panti," +
                        "panties," +
                        "payo," +
                        "pearlnecklace," +
                        "peck," +
                        "pecker," +
                        "peckerwood," +
                        "peehole," +
                        "pee-pee," +
                        "peepshow," +
                        "peepshpw," +
                        "pendy," +
                        "penetration," +
                        "peni5," +
                        "penile," +
                        "penis," +
                        "penises," +
                        "penthouse," +
                        "period," +
                        "perv," +
                        "phonesex," +
                        "phuk," +
                        "phuked," +
                        "phuking," +
                        "phukked," +
                        "phukking," +
                        "phungky," +
                        "phuq," +
                        "pi55," +
                        "picaninny," +
                        "piccaninny," +
                        "pickaninny," +
                        "piker," +
                        "pikey," +
                        "piky," +
                        "pimp," +
                        "pimped," +
                        "pimper," +
                        "pimpjuic," +
                        "pimpjuice," +
                        "pimpsimp," +
                        "pindick," +
                        "piss," +
                        "pissed," +
                        "pisser," +
                        "pisses ," +
                        "pisshead," +
                        "pissin ," +
                        "pissing," +
                        "pissoff ," +
                        "pistol," +
                        "pixie," +
                        "pixy," +
                        "playboy," +
                        "playgirl," +
                        "pocha," +
                        "pocho," +
                        "pocketpool," +
                        "pohm," +
                        "polack," +
                        "pom," +
                        "pommie," +
                        "pommy," +
                        "poontang," +
                        "pooper," +
                        "pooperscooper," +
                        "pooping," +
                        "poorwhitetrash," +
                        "popimp," +
                        "porchmonkey," +
                        "porn," +
                        "pornflick," +
                        "pornking," +
                        "porno," +
                        "pornography," +
                        "pornprincess," +
                        "poverty," +
                        "premature," +
                        "prick," +
                        "prickhead," +
                        "primetime," +
                        "propaganda," +
                        "prostitute," +
                        "protestant," +
                        "pu55i," +
                        "pu55y," +
                        "pubic," +
                        "pubiclice," +
                        "pudboy," +
                        "pudd," +
                        "puddboy," +
                        "puntang," +
                        "purinapricness," +
                        "pussie," +
                        "pussies," +
                        "pussy," +
                        "pussycat," +
                        "pussyeater," +
                        "pussyfucker," +
                        "pussylicker," +
                        "pussylips," +
                        "pussylover," +
                        "pussypounder," +
                        "pusy," +
                        "quashie," +
                        "queef," +
                        "queer," +
                        "quickie," +
                        "quim," +
                        "ra8s," +
                        "rabbi," +
                        "racial," +
                        "racist," +
                        "radical," +
                        "radicals," +
                        "raghead," +
                        "randy," +
                        "rape," +
                        "raped," +
                        "raper," +
                        "rapist," +
                        "rearend," +
                        "rearentry," +
                        "rectum," +
                        "redlight," +
                        "redneck," +
                        "reefer," +
                        "reestie," +
                        "refugee," +
                        "reject," +
                        "remains," +
                        "rentafuck," +
                        "republican," +
                        "retard," +
                        "retarded," +
                        "ribbed," +
                        "rigger," +
                        "rimjob," +
                        "rimming," +
                        "roach," +
                        "robber," +
                        "roundeye," +
                        "russki," +
                        "russkie," +
                        "sadis," +
                        "sadom," +
                        "samckdaddy," +
                        "sandm," +
                        "sandnigger," +
                        "scallywag," +
                        "schlong," +
                        "screw," +
                        "screwyou," +
                        "scrotum," +
                        "scum," +
                        "semen," +
                        "seppo," +
                        "servant," +
                        "sex," +
                        "sexed," +
                        "sexfarm," +
                        "sexhound," +
                        "sexhouse," +
                        "sexing," +
                        "sexkitten," +
                        "sexpot," +
                        "sexslave," +
                        "sextogo," +
                        "sextoy," +
                        "sextoys," +
                        "sexual," +
                        "sexually," +
                        "sexwhore," +
                        "sexy," +
                        "sexymoma," +
                        "sexy-slim," +
                        "shag," +
                        "shaggin," +
                        "shagging," +
                        "shawtypimp," +
                        "sheeney," +
                        "shhit," +
                        "shinola," +
                        "shit," +
                        "shitcan," +
                        "shitdick," +
                        "shite," +
                        "shiteater," +
                        "shited," +
                        "shitface," +
                        "shitfaced," +
                        "shitfit," +
                        "shitforbrains," +
                        "shitfuck," +
                        "shitfucker," +
                        "shitfull," +
                        "shithapens," +
                        "shithappens," +
                        "shithead," +
                        "shithouse," +
                        "shiting," +
                        "shitlist," +
                        "shitola," +
                        "shitoutofluck," +
                        "shits," +
                        "shitstain," +
                        "shitted," +
                        "shitter," +
                        "shitting," +
                        "shitty ," +
                        "shoot," +
                        "shooting," +
                        "shortfuck," +
                        "showtime," +
                        "sixsixsix," +
                        "sixtynine," +
                        "sixtyniner," +
                        "skankbitch," +
                        "skankfuck," +
                        "skankwhore," +
                        "skanky," +
                        "skankybitch," +
                        "skankywhore," +
                        "skinflute," +
                        "skum," +
                        "skumbag," +
                        "slant," +
                        "slanteye," +
                        "slapper," +
                        "slaughter," +
                        "slave," +
                        "slavedriver," +
                        "sleezebag," +
                        "sleezeball," +
                        "slideitin," +
                        "slime," +
                        "slimeball," +
                        "slimebucket," +
                        "slopehead," +
                        "slopey," +
                        "slopy," +
                        "slut," +
                        "sluts," +
                        "slutt," +
                        "slutting," +
                        "slutty," +
                        "slutwear," +
                        "slutwhore," +
                        "smack," +
                        "smackthemonkey," +
                        "smut," +
                        "snatch," +
                        "snatchpatch," +
                        "snigger," +
                        "sniggered," +
                        "sniggering," +
                        "sniggers," +
                        "snigger's," +
                        "sniper," +
                        "snot," +
                        "snowback," +
                        "snownigger," +
                        "sodom," +
                        "sodomise," +
                        "sodomite," +
                        "sodomize," +
                        "sodomy," +
                        "sonofabitch," +
                        "sonofbitch," +
                        "sooty," +
                        "spaghettibender," +
                        "spaghettinigger," +
                        "spank," +
                        "spankthemonkey," +
                        "sperm," +
                        "spermacide," +
                        "spermbag," +
                        "spermhearder," +
                        "spermherder," +
                        "spick," +
                        "spigotty," +
                        "spitter," +
                        "splittail," +
                        "spooge," +
                        "spreadeagle," +
                        "spunk," +
                        "spunky," +
                        "squaw," +
                        "stagg," +
                        "stiffy," +
                        "strapon," +
                        "stringer," +
                        "stripclub," +
                        "stroking," +
                        "stupid," +
                        "stupidfuck," +
                        "stupidfucker," +
                        "suck," +
                        "suckdick," +
                        "sucker," +
                        "suckme," +
                        "suckmyass," +
                        "suckmydick," +
                        "suckmytit," +
                        "suckoff," +
                        "suicide," +
                        "swallow," +
                        "swallower," +
                        "swalow," +
                        "swastika," +
                        "sweetness," +
                        "syphilis," +
                        "taboo," +
                        "tampon," +
                        "tantra," +
                        "tarbaby," +
                        "terror," +
                        "terrorist," +
                        "testicle," +
                        "testicles," +
                        "thicklips," +
                        "thirdeye," +
                        "thirdleg," +
                        "threesome," +
                        "threeway," +
                        "timbernigger," +
                        "tinkle," +
                        "titbitnipply," +
                        "titfuck," +
                        "titfucker," +
                        "titfuckin," +
                        "titjob," +
                        "titlicker," +
                        "titlover," +
                        "tittie," +
                        "titties," +
                        "titty," +
                        "toilet," +
                        "tongethruster," +
                        "tongue," +
                        "tonguethrust," +
                        "tonguetramp," +
                        "tortur," +
                        "torture," +
                        "tosser," +
                        "towelhead," +
                        "trailertrash," +
                        "tramp," +
                        "trannie," +
                        "tranny," +
                        "transexual," +
                        "transsexual," +
                        "transvestite," +
                        "triplex," +
                        "trisexual," +
                        "tuckahoe," +
                        "tunneloflove," +
                        "turd," +
                        "turnon," +
                        "twink," +
                        "twinkie," +
                        "twobitwhore," +
                        "unfuckable," +
                        "upskirt," +
                        "uptheass," +
                        "upthebutt," +
                        "urinary," +
                        "urinate," +
                        "urine," +
                        "usama," +
                        "uterus," +
                        "vagina," +
                        "vaginal," +
                        "vibrater," +
                        "vibrator," +
                        "vietcong," +
                        "violence," +
                        "virginbreaker," +
                        "vulva," +
                        "wanker," +
                        "wanking," +
                        "waysted," +
                        "weenie," +
                        "weewee," +
                        "welcher," +
                        "welfare," +
                        "wetback," +
                        "wetspot," +
                        "whacker," +
                        "whigger," +
                        "whiskeydick," +
                        "whiskydick," +
                        "whitenigger," +
                        "whitetrash," +
                        "whore," +
                        "whorefucker," +
                        "whorehouse," +
                        "wigger," +
                        "willie," +
                        "williewanker," +
                        "wuzzie," +
                        "xxx," +
                        "yankee," +
                        "zigabo," +
                        "zipperhead";*/

        //Above list will be managed when WebApplication is complete and
        //I build administration module. For now I have 6 entries below just as a proof of concept
        String list =   "porn" +
                "pussy" +
                "penis" +
                "dick" +
                "gay" +
                "lesbian";
        //etc... I limited the list because this system needs to be improved

        for(String offWord : list.split(",")){
            offensiveWords.add(offWord);
        }

        for(int i = 0; i < offensiveWords.size(); i++){
            String offensiveWord = offensiveWords.get(i);
            if(sentence.toLowerCase().contains(offensiveWord)){
                contains = true;
            }
        }




        return contains;
    }


}
